uber-go/mock

- gomock/controller.go
- gomock/doc.go
- gomock/matchers.go
- mockgen/internal/tests/import_embedded_interface/bugreport_test.go
- mockgen/internal/tests/import_embedded_interface/ersatz/ersatz.go
- mockgen/internal/tests/import_embedded_interface/faux/conflict.go
- mockgen/internal/tests/import_embedded_interface/faux/faux.go
- mockgen/internal/tests/import_embedded_interface/net_test.go
- mockgen/internal/tests/import_embedded_interface/other/ersatz/ersatz.go
- mockgen/internal/tests/import_embedded_interface/other/log/log.go
from Go 1.19, `go fmt` reformats doc comments.
https://go.dev/doc/go1.19#go-doc
> Go 1.19 adds support for links, lists, and clearer headings in doc comments. As part of this change, [gofmt](https://go.dev/cmd/gofmt) now reformats doc comments to make their rendered meaning clearer. See “[Go Doc Comments](https://go.dev/doc/comment)” for syntax details and descriptions of common mistakes now highlighted by gofmt. As another part of this change, the new package [go/doc/comment](https://go.dev/pkg/go/doc/comment/) provides parsing and reformatting of doc comments as well as support for rendering them to HTML, Markdown, and text.
> go fmt with Go 1.20

- gomock/callset.go
- gomock/callset_test.go
- gomock/controller.go
As suggested and outlined in #10
> Allow checking whether all expectations have been met

- gomock/controller.go
Originally discussed in https://github.com/golang/mock/issues/238.
This adds a functional option parameter to NewController to allow adding future configurations to control the behavior of Controller.
This will come in handy for implementing features like the one in #22.
> Add ControllerOption

- README.md
Go reference uses module name rather than repository URL as a package name.
> Fix Go reference URL in README

- gomock/callset.go
- gomock/callset_test.go
- gomock/controller.go
- gomock/example_test.go
- gomock/overridable_controller_test.go
This is an initial implementation of the proposal outlined in this issue, https://github.com/golang/mock/issues/685
> Implement OverridableController to allow for mock overrides

- sample/README.md
Hi,
Small change after the migration from golang to uber, so the users don't end up running the wrong tests.
> chore: update sample README after Uber migration

- mockgen/mockgen.go
- mockgen/mockgen_test.go
- mockgen/parse.go
- mockgen/reflect.go
This PR replaces the deprecated package `io/ioutil` with `io` and `os`.
> mockgen: replace io/ioutil with io and os package

- .github/workflows/release.yaml
- .github/workflows/test.yaml
From [actions/setup-go@v4.0.0](https://github.com/actions/setup-go/releases/tag/v4.0.0), the action caches the dependencies by default. We don't need to use actions/cache any more.
In addition, caching the dependencies requires `go.sum`. actions/checkout should precede actions/setup-go.
> use built-in cache of actions/setup-go

- CONTRIBUTING.md
- README.md
This PR changes URLs in the docs:
- replace `https://github.com/uber/mock` to `https://github.com/uber-go/mock`;
- replace `https://golang.org/` to `https://go.dev/`;
- update README with a link to CONTRIBUTIONS.md;
- fix grammar issues.
> Update resources links in README and CONTRIBUTIONS

- mockgen/model/model.go
> fix: register type with prefix

- mockgen/mockgen_test.go
The PR refactors `TestParsePackageImport` by:
- replacing `os.Setenv` with `t.Setenv`
- using `filepath.Join` instead of manual paths concatenating;
- adding missing error checks.
> Simplify TestParsePackageImport

- gomock/matchers.go
- gomock/matchers_test.go
- sample/imp4/imp4.go
- sample/user_test.go
`Cond` is a matcher allowing to rely on custom logic for complex matching scenarios.
It happened quite a few times that I had to leverage on the `DoAndReturn` to perform complex matching use cases, passing `gomock.Any()` as a matcher.
This would have allowed me to reduce a lot of complexity.
> feat: add Cond matcher 

- README.md
- gomock/controller.go
- gomock/controller_test.go
- gomock/doc.go
- gomock/matchers_test.go
- mockgen/internal/tests/aux_imports_embedded_interface/bugreport_test.go
- mockgen/internal/tests/custom_package_name/greeter/greeter_test.go
- mockgen/internal/tests/generated_identifier_conflict/bugreport_test.go
- mockgen/internal/tests/generics/source/mock_external_test.go
- mockgen/internal/tests/import_embedded_interface/bugreport_test.go
- mockgen/internal/tests/import_embedded_interface/net_test.go
- mockgen/internal/tests/overlapping_methods/overlap_test.go
- mockgen/internal/tests/panicing_test/panic_test.go
- mockgen/internal/tests/typed/bugreport_test.go
- mockgen/internal/tests/unexported_method/bugreport_test.go
- sample/concurrent/concurrent_test.go
- sample/user_test.go
This PR marks the function `ctrl.Finish` as `Deprecated`. It's no need to call this function starting from Go 1.14 when [T.Cleanup](https://pkg.go.dev/testing#T.Cleanup) was added.
> Deprecate the function ctrl.Finish()

- mockgen/mockgen.go
- fixed the following static check
- https://staticcheck.dev/docs/checks/#S1004
> Fix staticcheck S1004

- gomock/controller.go
We're about to release a new version, and we need to reach some more consensus on this decision. Undoing this deprecation for the time being for v0.3.0 release.
Ref: https://github.com/uber-go/mock/discussions/84.
> Undo deprecation of Controller.Finish()

- tools/cmd/extract-changelog/main.go
- tools/cmd/extract-changelog/main_test.go
- tools/go.mod
- tools/go.sum
This adds a tool for extracting changelog from the CHANGELOG.md file to ease up release notes creation.
> add extract-changelog

- .goreleaser.yml
binary uploads are failing because we moved this repo from the `uber` GitHub org to `uber-go` GitHub org, so uploads are getting 307 response.
> goreleaser config - fix owner

- gomock/matchers.go
- gomock/matchers_test.go
Closes #58.
Question: I was checking whether I handled copyright correctly, but `CONTRIBUTORS` seems very out of date?
> feat: add AnyOf that matches values that satisfy at least one matcher

- CONTRIBUTING.md
Now that we've removed the old CONTRIBUTORS file, update the CONTRIBUTING.md with a tip for signing Uber's CLA.
This follows the CONTRIBUTING.md tip for Fx.
ref: https://github.com/uber-go/fx/blob/master/CONTRIBUTING.md
> Add tip for signing Uber's CLA

- gomock/controller.go
- sample/concurrent/README.md
- sample/concurrent/concurrent_test.go
This PR is a proposal to add `mutex.Lock` on `Controller.Satisfied` to solve a race condition that can arise when two goroutines are involved in checking whether mock conditions have been satisfied.
The use case is illustrated in the `sample/concurrent` package - what I'm hoping to accomplish is where the test scenario contains one goroutine that runs indefinitely that calls mocked functions, I would like to use `Satisfied` as one of the conditions to trigger test assertions.
Tests added in `sample/concurrent` fails data race check without this change:
```
$ go test -race go.uber.org/mock/sample/concurrent
==================
WARNING: DATA RACE
Read at 0x00c000156350 by goroutine 9:
go.uber.org/mock/gomock.(*Call).satisfied()
/Users/dave/work/src/mock/gomock/call.go:307 +0x204 …
```
> fix: race condition on Controller.Satisfied

- gomock/matchers.go
- gomock/matchers_test.go
Closes #113 
Let me know if it's something you'd be interested in having - happy to make some tweaks if required
> feat: add Regex() matcher

- README.md
I forgot to do this when I created the last PR https://github.com/uber-go/mock/pull/72
> added a description of the exclude_interfaces flag to the README

- gomock/controller.go
- gomock/controller_test.go
- gomock/matchers.go
- gomock/mock_test.go
- gomock/string.go
- mockgen/mockgen.go
Fixes #116 
If your mock an interface that matches the fmt.Stringer interface:
```go
type Stringer interface {
String() string
}
```
Then your unit tests can deadlock if you provide that mock as an expected argument to a call that is not matched (i.e. fails the test).
Because, when printing the error message for the call that was not matched, it calls `String()` on all arguments that support it, including the mock.
But each call to a mock is protected with a mutex, and the previous call (that was not matched) has not yet exited.
The solution has two parts
1. During mock code generation (an existing part of this library) add a unique method on mocks (ISGOMOCK)
1. During test execution, whenever we are stringifying something that might be a mock, check if it is a mock (ISGOMOCK) that …
> fix: prevent stringer deadlock #116

- CHANGELOG.md
- gomock/call_test.go
- gomock/controller.go
- gomock/controller_test.go
This PR fixes typos and spelling errors in code and documentation.
> Correct typos in comments, test, and CHANGELOG

- README.md
The reference link `[golang-install]` has become unused after #8.
> doc: remove unused reference link

- gomock/matchers.go
- gomock/matchers_test.go
- sample/user_test.go
`gomock.Cond` at the moment expects an matcher function with the signature `func(x any) bool` requiring a manual cast to the expected type. By making this matcher generic the callback function can be typed removing the need for a manual cast to the expected type.
The change should be backwards compatible with existing tests using `gomock.Cond`.
> Make Cond Matcher generic

- gomock/controller.go
Finish no longer has to be explicitly called on Controller with defer if the Controller was created with testing.T.
We tried to just mark this as deprecated in #50 but doing so would break many users, so we reverted it in #85.
In doing so we dropped some wordings from the doc that marked Finished as unnecessary for most cases.
This PR fixes the docstring to guide users without explicitly marking the API deprecated.
> Clarify documentation on Finish

- .github/workflows/release.yaml
- .github/workflows/test.yaml
- go.mod
- go.sum
- mockgen/internal/tests/generics/go.mod
- mockgen/internal/tests/typed/go.mod
- tools/go.mod
This change updates all `go.mod` and ci workflows to only support go1.22 and go1.23.
Although this will force users to upgrade to go1.22 to use the next release, it is technically in line with our release policy (see: https://github.com/uber-go/mock?tab=readme-ov-file#supported-go-versions) and will allow us to merge #198 without using build tags for references to the new `*types.Alias` and `types.Unalias()`.
> Support Go 1.22 and Go 1.23

- mockgen/internal/tests/build_constraint/mock.go
Regenerates generated mocks after #191, which will fix failing tests.
> Regenerate generated mocks

- mockgen/gob.go
- mockgen/gob_test.go
- mockgen/mockgen.go
Change #207 replaced reflect mode with package mode. In doing so, we no longer had to create separate reflect programs that would encode the resulting package into a gob for the rest of mockgen to read from.
Because of that, we removed the `--exec_only` flag.
However, this flag was actually used to pass in programs that created gob encodings in other ways, allowing customization of the package loading and encoding portion of mockgen. As an alternative, this adds a new flag to mockgen `--model_gob`, which allows mockgen users to pass a path to a gob encoding of a `model.Package`, so that custom programs for encoding package information can still be used in conjunction with mockgen.
> Add gob mode to support custom package loading techniques in place of `--exec_only`

- .github/workflows/test.yaml
- bazel/.gitignore
- bazel/MODULE.bazel
- bazel/go.mod
- bazel/go.sum
- bazel/rules/BUILD.bazel
- bazel/rules/gomock.bzl
- bazel/rules/tools.go
- bazel/tests/README.rst
- bazel/tests/reflective/BUILD.bazel
- bazel/tests/reflective/client.go
- bazel/tests/reflective/client_test.go
- bazel/tests/source/BUILD.bazel
- bazel/tests/source/client.go
- bazel/tests/source/client_test.go
- bazel/tests/source/client_wrapper.go
- bazel/tests/source_with_importpath/BUILD.bazel
- bazel/tests/source_with_importpath/client.go
- bazel/tests/source_with_importpath/client_test.go
This PR copies the gomock definition and tests from rules_go with minimal changes:
* Replacing github.com/golang/mock with go.uber.org/mock
* Replacing `load` statements accordingly
* Setting up a Bazel and a Go module in the "bazel" directory
Note that the Go module uses v0.4.0 of go.uber.org/mock, because the latest version is no longer compatible with the gomock rule (https://github.com/bazel-contrib/rules_go/issues/4153). We will update the rule and mockgen version in subsequent PRs.
This is a first step in addressing #225
> Copying gomock definition and tests from rules_go

- README.md
- mockgen/archive.go
- mockgen/mockgen.go
- mockgen/model/model_gotypes.go
This adds support for a 3rd option for creating mocks after reflect and source-mode: the archive mode. Archive mode lets you load archive files to create mocks. This can come in handy for writing Bazel rules that produce intermediary archive files and automatically codegen mocks in Bazel environments.
Rebased version of #125
> Support for archive mode

- bazel/go.mod
- bazel/go.sum
- bazel/rules/gomock.bzl
Removes the broken reflect mode in the bazel aspect, in favor of archive mode which was landed in #258
> feat(bazel): support archive mode

- bazel/rules/gomock.bzl
The comments still reference golang/mock instead of uber-go/mock.
Update references to point to the correct repository.
> chore(bazel): fix gomock references in comments

- gomock/string.go
- gomock/string_test.go
This fixes an issue where we're trying to print the value of a nil Stringer which causes a panic instead of failing the test, hurting the debuggability of the failure.
Fixes #283.
> Fix panic when trying to print a nil Stringer
